Added environment variables
OTRChat/NodeChat pull request #67
Opened 2018-11-19 05:55 UTC by jtj9817

Added config_vars.env for the production-stage front-end component of NodeChat. PR fix for #52

2018-11-19 11:41 UTC, joshghent requested changes

2018-11-19 11:41 UTC, joshghent commented on config_vars.env
> +LOCAL_HOST_FRONTEND = 'http://localhost:9876'
Let's rename this to be "PORT" and call this file "sample.env"

2018-11-19 11:41 UTC, joshghent commented on config_vars.env
> +LOCAL_HOST_FRONTEND = 'http://localhost:9876'
Create another variable called "URL"

2018-11-19 11:41 UTC, joshghent commented on src/loginPage/loginPage.js
> +        this.socket = io(process.env.LOCAL_HOST_FRONTEND);
Please default the url and port to localhost:9876 or throw an error if we do not have this config item passed

2018-11-20 03:27 UTC, dnguneratne requested changes

2018-11-20 07:20 UTC, jtj9817 commented on package.json
> +    "dotenv": "^6.1.0",
Just quickly skimmed that doc. So based on understanding, I just have to rename the variables with a prefix of 'REACT_APP' and I can remove the dotenv package? Once I get confirmation on this, I'll make the necessary changes accordingly.

2018-11-20 09:33 UTC, joshghent approved these changes

2018-11-20 14:07 UTC, dnguneratne commented on package.json
> +    "dotenv": "^6.1.0",
Yes, that's right. You'll also need to rename `config_vars.env` file to `.env`.

The environment variable can be accessed like this: `process.env.REACT_APP_[variable_name]`.

2018-11-20 14:17 UTC, joshghent commented on package.json
> +    "dotenv": "^6.1.0",
Nah .env should be gitignored. .env has the personal tokens and private stuff. That is why you need to provide a sample.env that is then duplicated and renamed to `.env`

2018-11-27 23:04 UTC, joshghent requested changes
Could you please fix up the environment variable names please? And add the .env file to the gitignore

2022-05-25 18:28 UTC, closed without merging